### ISSUE TITLE
Release 1.1.8 unavailable

### ISSUE THREAD

**Issue by cthiebault** [jillesvangurp/es-kotlin-client#71]
It seems that version 1.1.8 was not published to jitpack.io: https://jitpack.io/com/github/jillesvangurp/es-kotlin-client/1.1.8 is empty...

```
Could not find com.github.jillesvangurp:es-kotlin-client:1.1.8.
        Searched in the following locations:
          - https://jitpack.io/com/github/jillesvangurp/es-kotlin-client/1.1.8/es-kotlin-client-1.1.8.pom
```

**Comment by jillesvangurp** [comment]
Thanks for letting me know; I'll look into what is going on there.

**Comment by jillesvangurp** [comment]
It looks like they were having some server issues. The build log is gone and it actually queued a new build for the same tag now.

I also tagged a 1.1.8.1 which seems to have built successfully:

https://jitpack.io/com/github/jillesvangurp/es-kotlin-client/1.1.8.1/build.log

Same commit hash. So no changes otherwise. So, either version should work now. I just rebuilt one of my projects against 1.1.8 and that seems to have worked.
